Add invoice date to material invoices
sascreative-IT/my-sas-ver2 pull request #78
Opened 2022-08-23 10:38 UTC by Aditha-Sansa

2022-08-24 04:39 UTC, nuke99 requested changes

2022-08-24 04:39 UTC, nuke99 commented on database/migrations/2022_08_23_071614_add_invoiced_date_column_to_material_invoices_table.php
> +        Schema::table('material_invoices', function (Blueprint $table) {
put a condition to run this only on production.

2022-08-24 04:39 UTC, nuke99 commented on database/migrations/2022_08_23_071614_add_invoiced_date_column_to_material_invoices_table.php
> +        $modelCollection = \App\Models\MaterialInvoice::all();
This should be inside a job which can be dispatched from the migration

2022-08-24 04:39 UTC, nuke99 commented on database/migrations/2022_08_23_084451_change_invoiced_date_column_to_non_nullable_material_invoices_table.php
> +    public function up()
why is this needed? Material doesn't need an invoiced date, right ?

2022-08-24 04:39 UTC, nuke99 commented on resources/js/Pages/Invoices/InvoiceShow.vue
> +        console.log(this.formatTime(this.invoice[0].created_at))
remove the console.log

2022-08-29 05:11 UTC, nuke99 commented on app/Jobs/FillInvoicedDate.php
> +        $modelCollection = \App\Models\MaterialInvoice::all();
only when invoice date is empty

2022-10-03 06:42 UTC, Aditha-Sansa commented on app/Jobs/FillInvoicedDate.php
> +        $modelCollection = \App\Models\MaterialInvoice::all();
This is fixed

2022-10-24 12:29 UTC, merged