Account invoice list and filters
sascreative-IT/my-sas-ver2 pull request #90
Opened 2022-11-15 16:34 UTC by nmsan

2022-11-15 17:50 UTC, nuke99 requested changes

2022-11-15 17:50 UTC, nuke99 commented on database/seeders/AccountInvoicesSeeder.php
> +        $this-> call(QuotationSeeder::class);
remove `$this-> call(QuotationSeeder::class);` and the `AccountInvoicesSeeder` class to the main database seeder

2022-11-16 04:18 UTC, nmsan commented on database/seeders/AccountInvoicesSeeder.php
> +        $this-> call(QuotationSeeder::class);
done

2022-11-16 04:19 UTC, nmsan commented on app/Http/Resources/Invoice/AccountInvoiceResource.php
> +class AccountInvoiceResource extends JsonResource
Now using a collection to solve pagination issue

2022-11-16 04:51 UTC, nuke99 commented on app/Http/Controllers/AccountInvoiceController.php
> +            'invoices' => new AccountInvoiceCollection($invoices),
we can also do this by `AccountInvoiceResource::collection($invoices)`

2022-11-18 05:16 UTC, nuke99 commented on app/Http/Controllers/AccountInvoiceController.php
> +//        dd($invoices);
remove this

2022-11-18 05:22 UTC, nuke99 requested changes

2022-11-18 05:22 UTC, nuke99 commented on database/seeders/AccountInvoicesSeeder.php
> +            'quotation_id' => 1,
Fetch this from static method from QuotationSeeder

2022-11-21 01:36 UTC, nmsan commented on app/Http/Controllers/AccountInvoiceController.php
> +            'invoices' => new AccountInvoiceCollection($invoices),
changed

2022-11-21 01:37 UTC, nmsan commented on app/Http/Controllers/AccountInvoiceController.php
> +//        dd($invoices);
removed

2022-11-21 01:37 UTC, nmsan commented on database/seeders/AccountInvoicesSeeder.php
> +            'quotation_id' => 1,
changed

2022-11-21 14:32 UTC, merged